export const CHANGE_SIZE = "CHANGE_SIZE";
export const GET_SIZES_SUCCESS = "GET_SIZES_SUCCESS";
export const GET_SIZES_ERROR = "GET_SIZES_ERROR";

export const GET_PIZZAS_SUCCESS = "GET_PIZZAS_SUCCESS";
export const GET_PIZZA_SUCCESS = "GET_PIZZA_SUCCESS";
export const GET_PIZZAS_FOR_MAINPAGE = "GET_PIZZAS_FOR_MAINPAGE";
export const GET_PRICE_FILTERED_PIZZAS_SUCCESS = "GET_PRICE_FILTERED_PIZZAS_SUCCESS"

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const CLEAN_CART = "CLEANc_CART";
